import { useAppDispatch, useAppSelector } from "./hooks";
import {
  movieSlice,
  moviesSlice,
  searchSlice,
  userSlice,
  resetMoviesSearch,
  getRandomMovies,
  loadMoreMovies,
  searchMovies,
  getMovieById,
  getRecommendations,
  setSearchRequest,
  setFilters,
  resetTypeFilter,
  resetYearFilter,
  resetSorting,
  getTrends,
  loadMoreTrends,
  searchTrends,
  resetTrendsSearch,
  signUp,
  signIn,
  signUserOut,
  reauthentificate,
  updateUserName,
  updateUserEmail,
  updateUserPassword,
  resetPassword,
  resetPasswordState,
  resetError,
  updateUserCredentials,
  toggleColorMode,
  addToFavorites,
  removeFromFavorites,
  searchInFavourites,
} from "./slices";

import { AppDispatch, RootState } from "./store";

export type { AppDispatch, RootState };

export {
  useAppDispatch,
  useAppSelector,
  movieSlice,
  moviesSlice,
  searchSlice,
  userSlice,
  resetMoviesSearch,
  getRandomMovies,
  loadMoreMovies,
  searchMovies,
  getMovieById,
  getRecommendations,
  setSearchRequest,
  setFilters,
  resetTypeFilter,
  resetYearFilter,
  resetSorting,
  getTrends,
  loadMoreTrends,
  searchTrends,
  resetTrendsSearch,
  signUp,
  signIn,
  signUserOut,
  reauthentificate,
  updateUserName,
  updateUserEmail,
  updateUserPassword,
  resetPassword,
  resetPasswordState,
  resetError,
  updateUserCredentials,
  toggleColorMode,
  addToFavorites,
  removeFromFavorites,
  searchInFavourites,
};
