import movieSlice, { getMovieById, getRecommendations } from "./movieSlice";
import moviesSlice, {
  getRandomMovies,
  loadMoreMovies,
  resetMoviesSearch,
  searchMovies,
} from "./moviesSlice";
import searchSlice, {
  resetSorting,
  resetTypeFilter,
  resetYearFilter,
  setFilters,
  setSearchRequest,
} from "./searchSlice";
import { getTrends, loadMoreTrends, searchTrends, resetTrendsSearch } from "./trendsSlice";
import userSlice, {
  addToFavorites,
  reauthentificate,
  removeFromFavorites,
  resetError,
  resetPassword,
  resetPasswordState,
  searchInFavourites,
  signIn,
  signUp,
  signUserOut,
  toggleColorMode,
  updateUserCredentials,
  updateUserEmail,
  updateUserName,
  updateUserPassword,
} from "./userSlice";

export {
  movieSlice,
  moviesSlice,
  searchSlice,
  userSlice,
  resetMoviesSearch,
  getRandomMovies,
  loadMoreMovies,
  searchMovies,
  getMovieById,
  getRecommendations,
  setSearchRequest,
  setFilters,
  resetTypeFilter,
  resetYearFilter,
  resetSorting,
  getTrends,
  loadMoreTrends,
  searchTrends,
  resetTrendsSearch,
  signUp,
  signIn,
  signUserOut,
  reauthentificate,
  updateUserName,
  updateUserEmail,
  updateUserPassword,
  resetPassword,
  resetPasswordState,
  resetError,
  updateUserCredentials,
  toggleColorMode,
  addToFavorites,
  removeFromFavorites,
  searchInFavourites,
};
